server:
  port: 8080

spring:
  application:
    name: Online-Video-Recoder
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:postgresql://localhost:5432/video_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql
logging:
  level:
    com.memory.onlinevideorecoder: debug

video:
  input-dir: /input
  output-dir: /output